/**
 * hsjry.com Inc.
 * Copyright (c) 2014-2019 All Rights Reserved.
 */
package com.david.study.maven.dao;


import com.david.study.maven.entity.ExceptionRetryExt;
import com.david.study.maven.entity.ExceptionRetryExtExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * 异常重试扩展Mapper
 * @author liangjf
 * @version $Id: ExceptionRetryExtMapper.java, v 1.0 2019年3月19日 下午7:02:08 liangjf Exp $
 * @since 1.0
 */
public interface ExceptionRetryExtMapper  {
	

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_retry
     *
     * @mbg.generated
     */
    int deleteByExample(ExceptionRetryExtExample example);

   /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table exception_retry
    *
    * @mbg.generated
    */
   int insertSelective(ExceptionRetryExt record);
    
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table exception_retry
	 *
	 * @mbg.generated
	 */
	List<ExceptionRetryExt> selectByExample(ExceptionRetryExtExample example);

//	List<ExceptionRetryDto> selectExtByExample(ExceptionRetryExtExample example);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table exception_retry
	 *
	 * @mbg.generated
	 */
	List<ExceptionRetryExt> selectNoTenantByExample(ExceptionRetryExtExample example);
	
   /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table exception_retry
    *
    * @mbg.generated
    */
   int updateByExampleSelective(@Param("record") ExceptionRetryExt record, @Param("example") ExceptionRetryExtExample example);

   /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table exception_retry
    *
    * @mbg.generated
    */
   int updateByPrimaryKeySelective(ExceptionRetryExt record);

}
