package com.david.study.maven.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ExceptionRetryExtExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exception_retry
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exception_retry
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exception_retry
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exception_retry
     *
     * @mbg.generated
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exception_retry
     *
     * @mbg.generated
     */
    protected Integer limit;


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_retry
     *
     * @mbg.generated
     */
    public ExceptionRetryExtExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_retry
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_retry
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_retry
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_retry
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_retry
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_retry
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_retry
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_retry
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_retry
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_retry
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_retry
     *
     * @mbg.generated
     */
    public void setOffset(Integer offset) {
        this.offset=offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_retry
     *
     * @mbg.generated
     */
    public Integer getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_retry
     *
     * @mbg.generated
     */
    public void setLimit(Integer limit) {
        this.limit=limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_retry
     *
     * @mbg.generated
     */
    public Integer getLimit() {
        return limit;
    }


	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exception_retry
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                return;
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                return;
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                return;
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInvokeIdIsNull() {
            addCriterion("invoke_id is null");
            return (Criteria) this;
        }

        public Criteria andInvokeIdIsNotNull() {
            addCriterion("invoke_id is not null");
            return (Criteria) this;
        }

        public Criteria andInvokeIdEqualTo(Long value) {
            addCriterion("invoke_id =", value, "invokeId");
            return (Criteria) this;
        }

        public Criteria andInvokeIdNotEqualTo(Long value) {
            addCriterion("invoke_id <>", value, "invokeId");
            return (Criteria) this;
        }

        public Criteria andInvokeIdGreaterThan(Long value) {
            addCriterion("invoke_id >", value, "invokeId");
            return (Criteria) this;
        }

        public Criteria andInvokeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("invoke_id >=", value, "invokeId");
            return (Criteria) this;
        }

        public Criteria andInvokeIdLessThan(Long value) {
            addCriterion("invoke_id <", value, "invokeId");
            return (Criteria) this;
        }

        public Criteria andInvokeIdLessThanOrEqualTo(Long value) {
            addCriterion("invoke_id <=", value, "invokeId");
            return (Criteria) this;
        }

        public Criteria andInvokeIdIn(List<Long> values) {
            addCriterion("invoke_id in", values, "invokeId");
            return (Criteria) this;
        }

        public Criteria andInvokeIdNotIn(List<Long> values) {
            addCriterion("invoke_id not in", values, "invokeId");
            return (Criteria) this;
        }

        public Criteria andInvokeIdBetween(Long value1, Long value2) {
            addCriterion("invoke_id between", value1, value2, "invokeId");
            return (Criteria) this;
        }

        public Criteria andInvokeIdNotBetween(Long value1, Long value2) {
            addCriterion("invoke_id not between", value1, value2, "invokeId");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNull() {
            addCriterion("tenant_id is null");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNotNull() {
            addCriterion("tenant_id is not null");
            return (Criteria) this;
        }

        public Criteria andTenantIdEqualTo(String value) {
            addCriterion("tenant_id =", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotEqualTo(String value) {
            addCriterion("tenant_id <>", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThan(String value) {
            addCriterion("tenant_id >", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThanOrEqualTo(String value) {
            addCriterion("tenant_id >=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThan(String value) {
            addCriterion("tenant_id <", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThanOrEqualTo(String value) {
            addCriterion("tenant_id <=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLike(String value) {
            addCriterion("tenant_id like", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotLike(String value) {
            addCriterion("tenant_id not like", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdIn(List<String> values) {
            addCriterion("tenant_id in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotIn(List<String> values) {
            addCriterion("tenant_id not in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdBetween(String value1, String value2) {
            addCriterion("tenant_id between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotBetween(String value1, String value2) {
            addCriterion("tenant_id not between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeIsNull() {
            addCriterion("business_code is null");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeIsNotNull() {
            addCriterion("business_code is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeEqualTo(String value) {
            addCriterion("business_code =", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeNotEqualTo(String value) {
            addCriterion("business_code <>", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeGreaterThan(String value) {
            addCriterion("business_code >", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeGreaterThanOrEqualTo(String value) {
            addCriterion("business_code >=", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeLessThan(String value) {
            addCriterion("business_code <", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeLessThanOrEqualTo(String value) {
            addCriterion("business_code <=", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeLike(String value) {
            addCriterion("business_code like", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeNotLike(String value) {
            addCriterion("business_code not like", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeIn(List<String> values) {
            addCriterion("business_code in", values, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeNotIn(List<String> values) {
            addCriterion("business_code not in", values, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeBetween(String value1, String value2) {
            addCriterion("business_code between", value1, value2, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeNotBetween(String value1, String value2) {
            addCriterion("business_code not between", value1, value2, "businessCode");
            return (Criteria) this;
        }
        
        public Criteria andBusinessNameIsNull() {
            addCriterion("business_name is null");
            return (Criteria) this;
        }

        public Criteria andBusinessNameIsNotNull() {
            addCriterion("business_name is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessNameEqualTo(String value) {
            addCriterion("business_name =", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotEqualTo(String value) {
            addCriterion("business_name <>", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameGreaterThan(String value) {
            addCriterion("business_name >", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameGreaterThanOrEqualTo(String value) {
            addCriterion("business_name >=", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameLessThan(String value) {
            addCriterion("business_name <", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameLessThanOrEqualTo(String value) {
            addCriterion("business_name <=", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameLike(String value) {
            addCriterion("business_name like", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotLike(String value) {
            addCriterion("business_name not like", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameIn(List<String> values) {
            addCriterion("business_name in", values, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotIn(List<String> values) {
            addCriterion("business_name not in", values, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameBetween(String value1, String value2) {
            addCriterion("business_name between", value1, value2, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotBetween(String value1, String value2) {
            addCriterion("business_name not between", value1, value2, "businessName");
            return (Criteria) this;
        }

        public Criteria andBeanNameIsNull() {
            addCriterion("bean_name is null");
            return (Criteria) this;
        }

        public Criteria andBeanNameIsNotNull() {
            addCriterion("bean_name is not null");
            return (Criteria) this;
        }

        public Criteria andBeanNameEqualTo(String value) {
            addCriterion("bean_name =", value, "beanName");
            return (Criteria) this;
        }

        public Criteria andBeanNameNotEqualTo(String value) {
            addCriterion("bean_name <>", value, "beanName");
            return (Criteria) this;
        }

        public Criteria andBeanNameGreaterThan(String value) {
            addCriterion("bean_name >", value, "beanName");
            return (Criteria) this;
        }

        public Criteria andBeanNameGreaterThanOrEqualTo(String value) {
            addCriterion("bean_name >=", value, "beanName");
            return (Criteria) this;
        }

        public Criteria andBeanNameLessThan(String value) {
            addCriterion("bean_name <", value, "beanName");
            return (Criteria) this;
        }

        public Criteria andBeanNameLessThanOrEqualTo(String value) {
            addCriterion("bean_name <=", value, "beanName");
            return (Criteria) this;
        }

        public Criteria andBeanNameLike(String value) {
            addCriterion("bean_name like", value, "beanName");
            return (Criteria) this;
        }

        public Criteria andBeanNameNotLike(String value) {
            addCriterion("bean_name not like", value, "beanName");
            return (Criteria) this;
        }

        public Criteria andBeanNameIn(List<String> values) {
            addCriterion("bean_name in", values, "beanName");
            return (Criteria) this;
        }

        public Criteria andBeanNameNotIn(List<String> values) {
            addCriterion("bean_name not in", values, "beanName");
            return (Criteria) this;
        }

        public Criteria andBeanNameBetween(String value1, String value2) {
            addCriterion("bean_name between", value1, value2, "beanName");
            return (Criteria) this;
        }

        public Criteria andBeanNameNotBetween(String value1, String value2) {
            addCriterion("bean_name not between", value1, value2, "beanName");
            return (Criteria) this;
        }

        public Criteria andClazzNameIsNull() {
            addCriterion("clazz_name is null");
            return (Criteria) this;
        }

        public Criteria andClazzNameIsNotNull() {
            addCriterion("clazz_name is not null");
            return (Criteria) this;
        }

        public Criteria andClazzNameEqualTo(String value) {
            addCriterion("clazz_name =", value, "clazzName");
            return (Criteria) this;
        }

        public Criteria andClazzNameNotEqualTo(String value) {
            addCriterion("clazz_name <>", value, "clazzName");
            return (Criteria) this;
        }

        public Criteria andClazzNameGreaterThan(String value) {
            addCriterion("clazz_name >", value, "clazzName");
            return (Criteria) this;
        }

        public Criteria andClazzNameGreaterThanOrEqualTo(String value) {
            addCriterion("clazz_name >=", value, "clazzName");
            return (Criteria) this;
        }

        public Criteria andClazzNameLessThan(String value) {
            addCriterion("clazz_name <", value, "clazzName");
            return (Criteria) this;
        }

        public Criteria andClazzNameLessThanOrEqualTo(String value) {
            addCriterion("clazz_name <=", value, "clazzName");
            return (Criteria) this;
        }

        public Criteria andClazzNameLike(String value) {
            addCriterion("clazz_name like", value, "clazzName");
            return (Criteria) this;
        }

        public Criteria andClazzNameNotLike(String value) {
            addCriterion("clazz_name not like", value, "clazzName");
            return (Criteria) this;
        }

        public Criteria andClazzNameIn(List<String> values) {
            addCriterion("clazz_name in", values, "clazzName");
            return (Criteria) this;
        }

        public Criteria andClazzNameNotIn(List<String> values) {
            addCriterion("clazz_name not in", values, "clazzName");
            return (Criteria) this;
        }

        public Criteria andClazzNameBetween(String value1, String value2) {
            addCriterion("clazz_name between", value1, value2, "clazzName");
            return (Criteria) this;
        }

        public Criteria andClazzNameNotBetween(String value1, String value2) {
            addCriterion("clazz_name not between", value1, value2, "clazzName");
            return (Criteria) this;
        }

        public Criteria andMethodNameIsNull() {
            addCriterion("method_name is null");
            return (Criteria) this;
        }

        public Criteria andMethodNameIsNotNull() {
            addCriterion("method_name is not null");
            return (Criteria) this;
        }

        public Criteria andMethodNameEqualTo(String value) {
            addCriterion("method_name =", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameNotEqualTo(String value) {
            addCriterion("method_name <>", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameGreaterThan(String value) {
            addCriterion("method_name >", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameGreaterThanOrEqualTo(String value) {
            addCriterion("method_name >=", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameLessThan(String value) {
            addCriterion("method_name <", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameLessThanOrEqualTo(String value) {
            addCriterion("method_name <=", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameLike(String value) {
            addCriterion("method_name like", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameNotLike(String value) {
            addCriterion("method_name not like", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameIn(List<String> values) {
            addCriterion("method_name in", values, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameNotIn(List<String> values) {
            addCriterion("method_name not in", values, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameBetween(String value1, String value2) {
            addCriterion("method_name between", value1, value2, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameNotBetween(String value1, String value2) {
            addCriterion("method_name not between", value1, value2, "methodName");
            return (Criteria) this;
        }

        public Criteria andParamsTypeIsNull() {
            addCriterion("params_type is null");
            return (Criteria) this;
        }

        public Criteria andParamsTypeIsNotNull() {
            addCriterion("params_type is not null");
            return (Criteria) this;
        }

        public Criteria andParamsTypeEqualTo(String value) {
            addCriterion("params_type =", value, "paramsType");
            return (Criteria) this;
        }

        public Criteria andParamsTypeNotEqualTo(String value) {
            addCriterion("params_type <>", value, "paramsType");
            return (Criteria) this;
        }

        public Criteria andParamsTypeGreaterThan(String value) {
            addCriterion("params_type >", value, "paramsType");
            return (Criteria) this;
        }

        public Criteria andParamsTypeGreaterThanOrEqualTo(String value) {
            addCriterion("params_type >=", value, "paramsType");
            return (Criteria) this;
        }

        public Criteria andParamsTypeLessThan(String value) {
            addCriterion("params_type <", value, "paramsType");
            return (Criteria) this;
        }

        public Criteria andParamsTypeLessThanOrEqualTo(String value) {
            addCriterion("params_type <=", value, "paramsType");
            return (Criteria) this;
        }

        public Criteria andParamsTypeLike(String value) {
            addCriterion("params_type like", value, "paramsType");
            return (Criteria) this;
        }

        public Criteria andParamsTypeNotLike(String value) {
            addCriterion("params_type not like", value, "paramsType");
            return (Criteria) this;
        }

        public Criteria andParamsTypeIn(List<String> values) {
            addCriterion("params_type in", values, "paramsType");
            return (Criteria) this;
        }

        public Criteria andParamsTypeNotIn(List<String> values) {
            addCriterion("params_type not in", values, "paramsType");
            return (Criteria) this;
        }

        public Criteria andParamsTypeBetween(String value1, String value2) {
            addCriterion("params_type between", value1, value2, "paramsType");
            return (Criteria) this;
        }

        public Criteria andParamsTypeNotBetween(String value1, String value2) {
            addCriterion("params_type not between", value1, value2, "paramsType");
            return (Criteria) this;
        }

        public Criteria andParamsValueIsNull() {
            addCriterion("params_value is null");
            return (Criteria) this;
        }

        public Criteria andParamsValueIsNotNull() {
            addCriterion("params_value is not null");
            return (Criteria) this;
        }

        public Criteria andParamsValueEqualTo(String value) {
            addCriterion("params_value =", value, "paramsValue");
            return (Criteria) this;
        }

        public Criteria andParamsValueNotEqualTo(String value) {
            addCriterion("params_value <>", value, "paramsValue");
            return (Criteria) this;
        }

        public Criteria andParamsValueGreaterThan(String value) {
            addCriterion("params_value >", value, "paramsValue");
            return (Criteria) this;
        }

        public Criteria andParamsValueGreaterThanOrEqualTo(String value) {
            addCriterion("params_value >=", value, "paramsValue");
            return (Criteria) this;
        }

        public Criteria andParamsValueLessThan(String value) {
            addCriterion("params_value <", value, "paramsValue");
            return (Criteria) this;
        }

        public Criteria andParamsValueLessThanOrEqualTo(String value) {
            addCriterion("params_value <=", value, "paramsValue");
            return (Criteria) this;
        }

        public Criteria andParamsValueLike(String value) {
            addCriterion("params_value like", value, "paramsValue");
            return (Criteria) this;
        }

        public Criteria andParamsValueNotLike(String value) {
            addCriterion("params_value not like", value, "paramsValue");
            return (Criteria) this;
        }

        public Criteria andParamsValueIn(List<String> values) {
            addCriterion("params_value in", values, "paramsValue");
            return (Criteria) this;
        }

        public Criteria andParamsValueNotIn(List<String> values) {
            addCriterion("params_value not in", values, "paramsValue");
            return (Criteria) this;
        }

        public Criteria andParamsValueBetween(String value1, String value2) {
            addCriterion("params_value between", value1, value2, "paramsValue");
            return (Criteria) this;
        }

        public Criteria andParamsValueNotBetween(String value1, String value2) {
            addCriterion("params_value not between", value1, value2, "paramsValue");
            return (Criteria) this;
        }

        public Criteria andErrorDetailIsNull() {
            addCriterion("error_detail is null");
            return (Criteria) this;
        }

        public Criteria andErrorDetailIsNotNull() {
            addCriterion("error_detail is not null");
            return (Criteria) this;
        }

        public Criteria andErrorDetailEqualTo(String value) {
            addCriterion("error_detail =", value, "errorDetail");
            return (Criteria) this;
        }

        public Criteria andErrorDetailNotEqualTo(String value) {
            addCriterion("error_detail <>", value, "errorDetail");
            return (Criteria) this;
        }

        public Criteria andErrorDetailGreaterThan(String value) {
            addCriterion("error_detail >", value, "errorDetail");
            return (Criteria) this;
        }

        public Criteria andErrorDetailGreaterThanOrEqualTo(String value) {
            addCriterion("error_detail >=", value, "errorDetail");
            return (Criteria) this;
        }

        public Criteria andErrorDetailLessThan(String value) {
            addCriterion("error_detail <", value, "errorDetail");
            return (Criteria) this;
        }

        public Criteria andErrorDetailLessThanOrEqualTo(String value) {
            addCriterion("error_detail <=", value, "errorDetail");
            return (Criteria) this;
        }

        public Criteria andErrorDetailLike(String value) {
            addCriterion("error_detail like", value, "errorDetail");
            return (Criteria) this;
        }

        public Criteria andErrorDetailNotLike(String value) {
            addCriterion("error_detail not like", value, "errorDetail");
            return (Criteria) this;
        }

        public Criteria andErrorDetailIn(List<String> values) {
            addCriterion("error_detail in", values, "errorDetail");
            return (Criteria) this;
        }

        public Criteria andErrorDetailNotIn(List<String> values) {
            addCriterion("error_detail not in", values, "errorDetail");
            return (Criteria) this;
        }

        public Criteria andErrorDetailBetween(String value1, String value2) {
            addCriterion("error_detail between", value1, value2, "errorDetail");
            return (Criteria) this;
        }

        public Criteria andErrorDetailNotBetween(String value1, String value2) {
            addCriterion("error_detail not between", value1, value2, "errorDetail");
            return (Criteria) this;
        }

        public Criteria andInvokeStatusIsNull() {
            addCriterion("invoke_status is null");
            return (Criteria) this;
        }

        public Criteria andInvokeStatusIsNotNull() {
            addCriterion("invoke_status is not null");
            return (Criteria) this;
        }

        public Criteria andInvokeStatusEqualTo(Integer value) {
            addCriterion("invoke_status =", value, "invokeStatus");
            return (Criteria) this;
        }

        public Criteria andInvokeStatusNotEqualTo(Integer value) {
            addCriterion("invoke_status <>", value, "invokeStatus");
            return (Criteria) this;
        }

        public Criteria andInvokeStatusGreaterThan(Integer value) {
            addCriterion("invoke_status >", value, "invokeStatus");
            return (Criteria) this;
        }

        public Criteria andInvokeStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("invoke_status >=", value, "invokeStatus");
            return (Criteria) this;
        }

        public Criteria andInvokeStatusLessThan(Integer value) {
            addCriterion("invoke_status <", value, "invokeStatus");
            return (Criteria) this;
        }

        public Criteria andInvokeStatusLessThanOrEqualTo(Integer value) {
            addCriterion("invoke_status <=", value, "invokeStatus");
            return (Criteria) this;
        }

        public Criteria andInvokeStatusIn(List<Integer> values) {
            addCriterion("invoke_status in", values, "invokeStatus");
            return (Criteria) this;
        }

        public Criteria andInvokeStatusNotIn(List<Integer> values) {
            addCriterion("invoke_status not in", values, "invokeStatus");
            return (Criteria) this;
        }

        public Criteria andInvokeStatusBetween(Integer value1, Integer value2) {
            addCriterion("invoke_status between", value1, value2, "invokeStatus");
            return (Criteria) this;
        }

        public Criteria andInvokeStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("invoke_status not between", value1, value2, "invokeStatus");
            return (Criteria) this;
        }

        public Criteria andInvokeTimesIsNull() {
            addCriterion("invoke_times is null");
            return (Criteria) this;
        }

        public Criteria andInvokeTimesIsNotNull() {
            addCriterion("invoke_times is not null");
            return (Criteria) this;
        }

        public Criteria andInvokeTimesEqualTo(Integer value) {
            addCriterion("invoke_times =", value, "invokeTimes");
            return (Criteria) this;
        }

        public Criteria andInvokeTimesNotEqualTo(Integer value) {
            addCriterion("invoke_times <>", value, "invokeTimes");
            return (Criteria) this;
        }

        public Criteria andInvokeTimesGreaterThan(Integer value) {
            addCriterion("invoke_times >", value, "invokeTimes");
            return (Criteria) this;
        }

        public Criteria andInvokeTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("invoke_times >=", value, "invokeTimes");
            return (Criteria) this;
        }

        public Criteria andInvokeTimesLessThan(Integer value) {
            addCriterion("invoke_times <", value, "invokeTimes");
            return (Criteria) this;
        }

        public Criteria andInvokeTimesLessThanOrEqualTo(Integer value) {
            addCriterion("invoke_times <=", value, "invokeTimes");
            return (Criteria) this;
        }

        public Criteria andInvokeTimesIn(List<Integer> values) {
            addCriterion("invoke_times in", values, "invokeTimes");
            return (Criteria) this;
        }

        public Criteria andInvokeTimesNotIn(List<Integer> values) {
            addCriterion("invoke_times not in", values, "invokeTimes");
            return (Criteria) this;
        }

        public Criteria andInvokeTimesBetween(Integer value1, Integer value2) {
            addCriterion("invoke_times between", value1, value2, "invokeTimes");
            return (Criteria) this;
        }

        public Criteria andInvokeTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("invoke_times not between", value1, value2, "invokeTimes");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exception_retry
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exception_retry
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}