package com.david.study.maven.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 异常登记dto
 * @author liangjf
 * @version $Id: ExceptionRetryDto.java, v 1.0 2019年3月19日 下午7:22:55 liangjf Exp $
 * @since 1.0
 */
public class ExceptionRetryDto implements Serializable {
	
    /**  */
	private static final long serialVersionUID = 587256237265127505L;

	/** 异常补偿ID */
    private Long invokeId;

    /** 业务编号 */
    private String businessCode;
    
    /** 业务名称 */
    private String businessName;

    /** bean名称 */
    private String beanName;

    /** 执行类名称（全路径） */
    private String clazzName;

    /** 方法名称 */
    private String methodName;

    /** 参数类型（全路径） */
    private String paramsType;

    /** 参数值（json格式） */
    private String paramsValue;

    /** 错误信息 */
    private String errorDetail;

    /** 执行状态 0-待执行 1-执行中  */
    private Integer invokeStatus;

    /** 执行次数  */
    private Integer invokeTimes;

    /** 创建时间 */
    private Date createTime;

    /** 更新时间 */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception_retry.invoke_id
     *
     * @return the value of exception_retry.invoke_id
     *
     * @mbg.generated
     */
    public Long getInvokeId() {
        return invokeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception_retry.invoke_id
     *
     * @param invokeId the value for exception_retry.invoke_id
     *
     * @mbg.generated
     */
    public void setInvokeId(Long invokeId) {
        this.invokeId = invokeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception_retry.business_code
     *
     * @return the value of exception_retry.business_code
     *
     * @mbg.generated
     */
    public String getBusinessCode() {
        return businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception_retry.business_code
     *
     * @param businessCode the value for exception_retry.business_code
     *
     * @mbg.generated
     */
    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode == null ? null : businessCode.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception_retry.business_name
     *
     * @return the value of exception_retry.business_name
     *
     * @mbg.generated
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception_retry.business_name
     *
     * @param businessName the value for exception_retry.business_name
     *
     * @mbg.generated
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName == null ? null : businessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception_retry.bean_name
     *
     * @return the value of exception_retry.bean_name
     *
     * @mbg.generated
     */
    public String getBeanName() {
        return beanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception_retry.bean_name
     *
     * @param beanName the value for exception_retry.bean_name
     *
     * @mbg.generated
     */
    public void setBeanName(String beanName) {
        this.beanName = beanName == null ? null : beanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception_retry.clazz_name
     *
     * @return the value of exception_retry.clazz_name
     *
     * @mbg.generated
     */
    public String getClazzName() {
        return clazzName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception_retry.clazz_name
     *
     * @param clazzName the value for exception_retry.clazz_name
     *
     * @mbg.generated
     */
    public void setClazzName(String clazzName) {
        this.clazzName = clazzName == null ? null : clazzName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception_retry.method_name
     *
     * @return the value of exception_retry.method_name
     *
     * @mbg.generated
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception_retry.method_name
     *
     * @param methodName the value for exception_retry.method_name
     *
     * @mbg.generated
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception_retry.params_type
     *
     * @return the value of exception_retry.params_type
     *
     * @mbg.generated
     */
    public String getParamsType() {
        return paramsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception_retry.params_type
     *
     * @param paramsType the value for exception_retry.params_type
     *
     * @mbg.generated
     */
    public void setParamsType(String paramsType) {
        this.paramsType = paramsType == null ? null : paramsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception_retry.params_value
     *
     * @return the value of exception_retry.params_value
     *
     * @mbg.generated
     */
    public String getParamsValue() {
        return paramsValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception_retry.params_value
     *
     * @param paramsValue the value for exception_retry.params_value
     *
     * @mbg.generated
     */
    public void setParamsValue(String paramsValue) {
        this.paramsValue = paramsValue == null ? null : paramsValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception_retry.error_detail
     *
     * @return the value of exception_retry.error_detail
     *
     * @mbg.generated
     */
    public String getErrorDetail() {
        return errorDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception_retry.error_detail
     *
     * @param errorDetail the value for exception_retry.error_detail
     *
     * @mbg.generated
     */
    public void setErrorDetail(String errorDetail) {
        this.errorDetail = errorDetail == null ? null : errorDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception_retry.invoke_status
     *
     * @return the value of exception_retry.invoke_status
     *
     * @mbg.generated
     */
    public Integer getInvokeStatus() {
        return invokeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception_retry.invoke_status
     *
     * @param invokeStatus the value for exception_retry.invoke_status
     *
     * @mbg.generated
     */
    public void setInvokeStatus(Integer invokeStatus) {
        this.invokeStatus = invokeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception_retry.invoke_times
     *
     * @return the value of exception_retry.invoke_times
     *
     * @mbg.generated
     */
    public Integer getInvokeTimes() {
        return invokeTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception_retry.invoke_times
     *
     * @param invokeTimes the value for exception_retry.invoke_times
     *
     * @mbg.generated
     */
    public void setInvokeTimes(Integer invokeTimes) {
        this.invokeTimes = invokeTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception_retry.create_time
     *
     * @return the value of exception_retry.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception_retry.create_time
     *
     * @param createTime the value for exception_retry.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception_retry.update_time
     *
     * @return the value of exception_retry.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception_retry.update_time
     *
     * @param updateTime the value for exception_retry.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}